### ISSUE TITLE
If sensor fails in running system, endless loop occurs

### ISSUE THREAD

**Issue by MTJoker** [nuccleon/HomieDHT#2]
If the sensor fails during normal system operation (tested with BME280), an endless loop occurs during  BME280_Impl::readSensor(). Here, bme.takeForcedMeasurement() is called, which loops forever until a successful readout.
This kills the system, as it seems like no watchdog is triggered (maybe disabled in Homie?).

**Comment by beckenc** [comment]
fixed with 1c487b0
